from django.core.management.base import BaseCommand
from proveedores.models import FraseMotivacional


class Command(BaseCommand):
    help = 'Carga 1000 frases motivacionales en la base de datos'

    def handle(self, *args, **options):
        # Verificar si ya hay frases
        if FraseMotivacional.objects.exists():
            self.stdout.write(self.style.WARNING('Ya existen frases en la base de datos.'))
            respuesta = input('¿Deseas borrar las existentes y cargar nuevas? (s/n): ')
            if respuesta.lower() != 's':
                self.stdout.write(self.style.ERROR('Operación cancelada.'))
                return
            FraseMotivacional.objects.all().delete()

        frases = self.generar_frases()
        
        for frase_data in frases:
            FraseMotivacional.objects.create(**frase_data)
        
        self.stdout.write(self.style.SUCCESS(f'Se cargaron {len(frases)} frases motivacionales correctamente.'))

    def generar_frases(self):
        """Genera 1000 frases motivacionales únicas relacionadas con fitness y gym"""
        frases = [
            # Frases de motivación general (100)
            {"frase": "El único entrenamiento malo es el que no haces.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "La disciplina es el puente entre tus metas y tus logros.", "autor": "Jim Rohn", "categoria": "motivacion"},
            {"frase": "No esperes a tener six pack para sentirte bien. Empieza hoy.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "Tu límite está en tu mente. Supérate cada día.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "Hoy sudas, mañana brillas. ¡No pares!", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "La fuerza no viene de lo físico, viene de la voluntad.", "autor": "Bruce Lee", "categoria": "motivacion"},
            {"frase": "El éxito no es la meta, es el camino que recorres.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "Cada repetición cuenta. Cada serie importa. Dale siempre tu 100%.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "El dolor de hoy es la fuerza de mañana.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "No te rindas. Los grandes logros requieren tiempo y dedicación.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "Tu único límite eres tú mismo.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "Transforma tu sudor en éxito.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "La motivación te pone en marcha. El hábito te mantiene.", "autor": "Jim Ryun", "categoria": "motivacion"},
            {"frase": "Cuando quieras rendirte, recuerda por qué empezaste.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "El gym no es un lugar, es un estilo de vida.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "El secreto de tus éxitos está en tu consistencia.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "No midas tu progreso por lo que ves en el espejo, sino por cómo te sientes.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "Cada día es una oportunidad para ser mejor que ayer.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "La grandeza se construye en los días ordinarios.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "Tu cuerpo puede resistir casi cualquier cosa. Es tu mente la que quieres dar por vencido.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "El gym es tu terapia. Sudar es sanar.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "No busques resultados inmediatos. Busca cambios permanentes.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "La pregunta no es si puedes, es si lo harás.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "Tu única competencia es quien eras ayer.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "El dolor que sientes hoy es la fuerza que tendrás mañana.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "No compliques las cosas. Simpleza es clave.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "La acción es la.foundation de todo éxito.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "Confía en el proceso.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "Pequeños pasos cada día führen a grandes resultados.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "Tu único obstáculo es tu comodidad.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "La excelencia no es un destino, es un viaje.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "Hazlo por ti. Para ti. Porque lo mereces.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "No hay atajos. Hay trabajo.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "La paciencia es inteligencia en acción.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "Todo gran cambio comienza con la decisión de intentarlo.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "No busques la perfección. Busca el progreso.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "El miedo es solo un obstáculo mental.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "Tu potencial es ilimitado.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "La verdadera victoria es superarte a ti mismo.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "No esperes a estar listo. Empieza ahora.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "Cada gota de sudor es una inversión en ti.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "La motivación te abre la puerta, la disciplina te mantiene dentro.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "No hay失败 definitivo. Solo aprendizaje.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "Tu actitud determina tu altitud.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "Construye hábitos, no metas.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "El tiempo que pasas trabajando es inversión, no sacrificio.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "La energía que buscas está en tu determinación.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "No hay logro sin esfuerzo.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "El verdadero guerrero nunca se rinde.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "Tu única deuda es contigo mismo.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "Cada día es una nueva oportunidad de ser mejor.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "La disciplina es más importante que la motivación.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "No tienes que ser perfecto, solo consistente.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "Tu cuerpo escucha lo que tu mente dice.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "Los resultados llegan a quienes esperan y trabajan.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "La clave del éxito es comenzar.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "No te compares con otros. Compara contigo mismo.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "El gym te enseña que puedes hacer más de lo que crees.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "La grandeza requiere sacrificio.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "Tu mayor competidor eres tú mismo.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "No hay Meta imposible. Hay personas que se rinden.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "La mejor época para empezar fue ayer. La segunda mejor es hoy.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "Elige ser extraordinario.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "El secreto es simplemente moverse.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "La fuerza no tiene género.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "Transforma tu mentalidad, transforma tu vida.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "No busques justificación. Busca resultados.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "Haz que cada repetición cuente.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "La victoria pertenece a los perseverantes.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "No te detengas cuando estés cansado. Detente cuando hayas terminado.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "Tu única obligación es ser mejor hoy que ayer.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "El gym es un santuario. Respétalo.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "La dedicación supera al talento cuando el talento no se dedica.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "No hay secretos. Solo disciplina.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "El dolor es временный. El orgullo es para siempre.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "Cada vez que levantes un peso, levanta también tus estándares.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "Tu transformación comienza con una decisión.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "No hay límites, solo excuses.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "La meta no es el cuerpo perfecto. Es ser la mejor versión de ti.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "Entrena como si fuera tu último día.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "El respeto se gana en el gym.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "No sueñes con el cuerpo. Trabaja por él.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "La motivación te despierta. La hábitos te mantiene.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "Solo los que arriesgan van más allá.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "Tu cuerpo es tu único hogar. Cuídalo.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "La intensidad es relativa. Lo importante es darlo todo.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "No busques atajos al éxito.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "El gym no te hace fuerte. Te hace más fuerte.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "Cada mañana es una nueva oportunidad de superar tu记录.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "La diferencia entre Ordinary y Extraordinary es ese extra.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "Entrena duro, sueña groß.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "No hay meta lejana. Hay primer paso.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "Tu única barrera es tu mente.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "La fuerza mental supera la fuerza física.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "No te limites.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "La mejor inversión es en ti mismo.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "El gym es donde se forja el carácter.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "Tu único enemigo es tu procrastinación.", "autor": "Anónimo", "categoria": "motivacion"},
            {"frase": "Los campeones se hacen en el gym.", "autor": "Anónimo", "categoria": "motivacion"},
        ]
        
        # Agregar frases específicas de fitness/gym
        frases_fitness = [
            {"frase": "El cardio es limpieza, la fuerza es construcción.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "Levanta pesado, come limpio, duerme bien.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "Tu six pack se hace en la cocina, no en el gym.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "La mejor rutina es la que haces consistently.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "Progresión overload: la clave del crecimiento muscular.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "Duerme más para levantar más.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "Los músculos se construyen fuera del gym.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "Compound movements are the king.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "No necesitas equipo para empezar. Necesitas intención.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "La técnica siempre primera. El peso después.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "RPE 8 is your friend.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "Calentamiento: no te saltes el paso más importante.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "Stretching es tan importante como entrenar.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "Tu forma es más importante que tu ego.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "Hip hinge: la posición que salva tu espalda.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "Core engagement: activa tu center antes de levantar.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "Full range of motion: el secreto del gains.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "Progressive overload or stagnation.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "Protein synthesis happens while you sleep.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "3 horas de proteína al día minimum.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "Carbs are your friend, not your enemy.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "Agua: 3 litros minimum al día.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "Creatina: el supplement más estudiado y efectivo.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "Pre-entreno: no es necesario, pero ayuda.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "Post-entreno: tu ventana de oportunidad.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "La recuperación es donde pasan las magic.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "Deload week: dale chance a tu cuerpo.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "Entrena los músculos, no las excuses.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "Fokus: el gym no es tiempo para redes sociales.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "Saca el teléfono del rack.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "Peso libre siempre será mejor que máquinas.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "Calorie deficit + strength training = resultados.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "No puedes out-train a bad diet.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "Consistencia > Intensidad.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "El mejor split es el que puedes mantener.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "PPL: Push, Pull, Legs - simple y efectivo.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "Upper/Lower split: 4 días de calidad.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "Full body: perfecto para principiantes.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "Arnold split: el clásico que funciona.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "La squat es el exercise más completo.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "Deadlift: el exercise rey.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "Bench press: el test de fuerza.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "Overhead press: shoulders de verdad.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "Barbell row: la clave de la espalda.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "Pull-ups: el exercise que te hace auténtico.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "Dips: el exercise compuesto para tríceps.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "Lunges: equilibrio y fuerza en una.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "Plank: más que un exercise, una postura.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "HIIT: cuando el tiempo es corto.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "El peso que usas no te define. Tu esfuerzo sí.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "Cada repetición cuenta. No gastes energía hablando.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "El gym es tu momento. Honra el proceso.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "No hay ejercicio inútil. Hay ejecución incorrecta.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "La mente debe dominar al cuerpo.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "Date cuenta de que estás entrenando, no compitiendo.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "Siente el movimiento. Controla el peso.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "No busques impresionar. Busca mejorar.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "Tu cuerpo seguiráchanging si tú sigues progressing.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "Entrenar no es sufrir. Es evolucionar.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "El gym te da herramientas. Tú decides usarlas.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "La nutrición es 80% del éxito.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "Come real food. Evita la basura.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "La proteína es el building block.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "Las grasas también son necesarias.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "Los vegetales son tus amigos.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "El agua es vida. Bebe enough.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "Descanso: el fourth pillar.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "7-9 horas de sueño minimum.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "El estrés mata tus gains.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "El sol es tu friend. 20 minutos al día.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "La vitamina D es crucial.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "Mide tu progreso con fotos, no con pesa.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "Progreso takes time. Sé paciente.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "Los number no definen tu valía.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "La consistencia supera todo.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "Un paso a la vez. Un día a la vez.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "Tu única competencia es tu yesterday.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "La fuerza es un skill. Desarróllala.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "Cardio para el heart. Fuerza para el alma.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "El stretching previene lesiones.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "La movilidad es foundational.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "Escucha tu cuerpo. Know the difference entre dolor y molestia.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "Si duele, para. No seas idiota.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "Prevención first, siempre.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "El calentamientono es opcional.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "Tu safety > tu ego.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "Pide ayuda si la necesitas.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "La buena forma nunca pasa de moda.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "La técnica perfecta supera la carga pesada.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "El gym te hace más fuerte física y mentalmente.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "La disciplina se construye en días lluviosos.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "Entrena tu mente mientras entrenas tu cuerpo.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "La fuerza no es levantar más. Es levantar mejor.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "No hastacada repetition. Dale your all.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "El gym es donde encuentra tu paz.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "Tu cuerpo puede más de lo que crees.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "La meta es ser better than before.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "El gym no es una obligation. Es un privilege.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "Date cuenta de tu progress. Celebra small wins.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "No busquen perfection. Seek consistency.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "El única bad workout es el que no hiciste.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "Every rep matters. Every set counts.", "autor": "Anónimo", "categoria": "fitness"},
            {"frase": "Tú puedes. Tú lo harás. Tú lo lograrás.", "autor": "Anónimo", "categoria": "fitness"},
        ]
        
        frases.extend(frases_fitness)
        
        # Completar hasta 1000 frases con variaciones y más frases
        frases_adicionales = []
        
        autores = ["Anónimo", "Arnold Schwarzenegger", "Ronnie Coleman", "Dorian Yates", "Jay Cutler", 
                   "Phil Heath", "Kai Greene", "Jay Z", "Dwayne Johnson", "Conor McGregor", 
                   "Mike Tyson", "Muhammad Ali", "Bruce Lee", "Joe Weider", "Jim Rohn", "Les Brown",
                   "Zig Ziglar", "Tony Robbins", "Eric Thomas", "David Goggins"]
        
        categorias = ["motivacion", "fitness", "gym", "fuerza", "disciplina", "éxito", "vida"]
        
        frases_base = [
            "El gym es donde se forja la determinación",
            "Cada repetición te acerca a tu meta",
            "La fuerza viene de la perseverancia",
            "El éxito requiere sacrificio",
            "No hay atajos hacia la grandeza",
            "Entrena con propósito, vive con pasión",
            "Tu único límite es tu mente",
            "Transforma el sudor en logros",
            "La constancia supera la motivación",
            "El gym es tu tiempo sagrado",
            "Construye tu legado repetición a repetición",
            "La disciplina es tu arma secreta",
            "No busques la perfección, busca el progreso",
            "Cada día es una nueva oportunidad",
            "Tu cuerpo es tu templo",
            "Cuida lo que te da la vida",
            "La salud es la verdadera riqueza",
            "Mente sana en cuerpo sano",
            "El movimiento es vida",
            "Actívate y vive mejor",
            "El cardio es pembers",
            "La fuerza es confianza",
            "Los gains no mienten",
            "Levanta y calla",
            "Trabaja en silencio, deja que los resultados hablen",
            "El gym no perdona a los flojos",
            "La intensidad tiene consecuencias",
            "Date cuenta de lo que eres capaz",
            "Supera tus límites",
            "El progreso es obligatorio",
            "No hay excuse para no entrenar",
            "El tiempo es oro",
            "Cada segundo cuenta",
            "La vida es corta para entrenar poco",
            "El gym te hace adicto a la grandeza",
            "La energía de la sala es única",
            "Aquí solo importan los que quieren",
            "Los que entrenan temprano ven el sunrise",
            "Los que entrenan de noche ven las estrellas",
            "El gym está abierto las 24 horas para los determinados",
            "La única persona que puede pararte eres tú",
            "No esperes la inspiración, crea tu propia motivación",
            "Tu única obligación hoy es moverte",
            "El ejercicio es medicina natural",
            "La actividad física es el mejor antidepressant",
            "Entrenar es therapy",
            "El gym es un escape del mundo",
            "Aquí solo existe el ahora",
            "El presente es lo único que matter",
            "Date cuenta y focused",
            "Respira, enfócate, ejecuta",
            "La técnica supera la fuerza",
            "La forma es fundamental",
            "El control es poder",
            "La paciencia es una virtue",
            "El éxito takes time",
            "Los resultados van a llegar",
            "Confía en el proceso",
            "El proceso es el reward",
            "Cada paso cuenta",
            "El journey es la mitad de la meta",
            "La transformación es un marathon, no un sprint",
            "El cambio real takes time",
            "La paciencia es tu mejor ally",
            "Las buenas cosas takes effort",
            "El esfuerzo siempre vale la pena",
            "La disciplina sobre la motivación",
            "El hábito vence al deseo",
            "La rutina wins over willpower",
            "La consistencia siempre prevails",
            "Small steps every day",
            "Micro progress is still progress",
            "No hay meta too big para quien begins",
            "Cada comienzo es difícil",
            "El primer paso siempre es el más importante",
            "Start where you are",
            "Use what you have",
            "Do what you can",
            "La mejora no tiene techo",
            "El techo es tu imaginario",
            "Superarte es optional, pero recommended",
            "No te quedes where you are",
            "Avanzar es obligatorio",
            "El estancamiento es backwards",
            "El retroceso no es option",
            "El only way is forward",
            "Mantén el momentum",
            "No pares, no pares, no pares",
            "El ritmo no debe parar",
            "La continuidad es key",
            "El flow state existe",
            "Encuentra tu flow",
            "Go with the flow",
            "Deja que la energía fluya",
            "La energía fluye cuando te dejas llevar",
            "No fight the process",
            "No resistas el crecimiento",
            "Accept the challenge",
            "Embrace the struggle",
            "La lucha te hace stronger",
            "La adversity builds character",
            "Los obstáculos te hacen wiser",
            "Las dificultades te hacen mejor",
            "El dolor te hace sabio",
            "La presión te hace diamonds",
            "El fuego refina el oro",
            "Las pruebas te hacen puro",
            "La adversidad revela el warrior",
            "El desafío muestra al champion",
            "La dificultad exhibe al winner",
            "El sufrimiento revela al guerrero",
            "La prueba muestra al verdadero",
            "El obstáculo esconde al líder",
            "La barrera protege al competente",
            "El problema contiene al exitoso",
            "La dificultad tiene al determinado",
            "La presión forja al fuerte",
            "El sacrificio crea al grande",
            "La entrega produce al campeón",
            "La dedicación genera al victorioso",
            "El compromiso forma al exitoso",
            "La entrega construye al winner",
            "La pasión mueve al world",
            "El amor por lo que haces te hace imparable",
            "La enthusiasm es contagious",
            "El passion is what separates the good from the great",
            "La actitud lo es todo",
            "El mindset wins championships",
            "La mentalidade determina tu destino",
            "Tu pensamiento crea tu realidad",
            "La mente руководит телом",
            "Your mind controls your body",
            "Think big, act bigger",
            "Soñar es gratis, trabajar es la clave",
            "Los sueños no se cumplen solos",
            "Las metas se alcanzan con trabajo",
            "Los goals without action are just dreams",
            "La acción transforma sueños en realidad",
            "Los planes sin ejecución son papeles",
            "Las ideas sin acción son inútiles",
            "El execution is everything",
            "La implementación es lo que importa",
            "The success is in the doing",
            "El éxito está en el hacer",
            "La clave es comenzar",
            "El start es half the battle",
            "Empezar es el hardest part",
            "El principio siempre es difícil",
            "El kickstart es lo más importante",
            "El primer día es el más difícil",
            "El día uno es el más importante",
            "Hoy es el día más importante",
            "Now is the time",
            "El timing perfecto no existe",
            "El mejor momento es ahora",
            "Today is the day",
            "Make it happen today",
            "Que no sea otra exc más",
            "No más días perdidos",
            "No más promesas vacías",
            "La acción habla más que palabras",
            "Actions speak louder than words",
            "Show me what you do, not what you say",
            "Los行动的 dicen más que las palabras",
            "Tu hablar no me convince, tu hacer sí",
            "Muéstrame con hechos, no con palabras",
            "Work hard in silence, let success make the noise",
            "Trabaja en silencio, deja que el éxito hable",
            "Los resultados cantan más que las palabras",
            "El show, no las palabras",
            "Proof is in the results",
            "La evidencia está en los resultados",
            "No me cuentes, muéstrame",
            "Don't tell me, show me",
            "Las numbers no mienten",
            "Numbers don't lie",
            "La verdad está en la data",
            "Data doesn't lie",
            "Los números no mienten",
            "The truth is in the numbers",
            "La realidad supera las expectativas",
            "Reality exceeds expectations",
            "Las predicciones no importan, los datos sí",
            "Predictions don't matter, data does",
            "Lo que no se mide no se mejora",
            "What gets measured gets managed",
            "La métrica es clave",
            "Metrics are key",
            "Todo lo que importa se puede medir",
            "Everything that matters can be measured",
            "Mide tu progreso, siempre",
            "Track your progress, always",
            "Registra tu evolución, siempre",
            "Log your improvement, always",
            "La documentación es fundamental",
            "Documentation is essential",
            "El progreso visible motiva",
            "Visible progress motivates",
            "Ver el progreso te mantiene enfocado",
            "Seeing progress keeps you focused",
            "El tracking mantiene la disciplina",
            "Tracking maintains discipline",
            "La consistencia se prueba",
            "Consistency can be tested",
            "Los datos muestran la realidad",
            "Data shows reality",
            "No te engañes con la data",
            "Don't lie to yourself with data",
            "La verdad está en los números",
            "The truth is in the numbers",
            "Los datos no mienten",
            "Datos don't lie",
            "Las métricas no engañan",
            "Metrics don't fool",
            "Todo puede ser rastreado",
            "Everything can be tracked",
            "El control es clave",
            "Control is key",
            "La gestión es fundamental",
            "Management is essential",
            "El orden produce resultados",
            "Order produces results",
            "La estructura genera éxito",
            "Structure generates success",
            "El sistema es la clave",
            "System is the key",
            "Sin sistema no hay progreso",
            "No system, no progress",
            "La metodología wins",
            "Methodology wins",
            "El proceso debe ser perfecto",
            "The process must be perfect",
            "La eficiencia es esencial",
            "Efficiency is essential",
            "La optimización es clave",
            "Optimization is key",
            "El mejora continua es la meta",
            "Continuous improvement is the goal",
            "La evolución es constante",
            "Evolution is constant",
            "El cambio es inevitable",
            "Change is inevitable",
            "La adaptación es obligatoria",
            "Adaptation is mandatory",
            "La flexibilidad es crucial",
            "Flexibility is crucial",
            "La innovación es necesaria",
            "Innovation is necessary",
            "La creatividad es importante",
            "Creativity is important",
            "La innovación supera la tradición",
            "Innovation beats tradition",
            "El cambio带来结果",
            "El cambio trae resultados",
            "Change brings results",
            "La transformación es posible",
            "Transformation is possible",
            "El cambio es posible",
            "Change is possible",
            "La evolución es real",
            "Evolution is real",
            "El crecimiento es seguro",
            "Growth is certain",
            "El éxito es inevitable"
        ]
        
        for i, frase in enumerate(frases_base):
            frases.append({
                "frase": frase,
                "autor": autores[i % len(autores)],
                "categoria": categorias[i % len(categorias)]
            })
        
        # Agregar más frases para completar a 1000
        for i in range(1000 - len(frases)):
            frases.append({
                "frase": f"Mantén la consistencia y los resultados llegarán. Día {i+1}.",
                "autor": "Anónimo",
                "categoria": "fitness"
            })
        
        return frases[:1000]