# Generated by Django 4.2 on 2026-03-11 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='planes/'),
        ),
    ]
