# Generated by Django 4.2.16 on 2026-04-07 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0003_plan_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='tipo',
            field=models.CharField(blank=True, choices=[('1_dia', '1 Día'), ('7_dias', '7 Días'), ('1_mes', '1 Mes'), ('3_mes', '3 Meses'), ('6_meses', '6 Meses'), ('1_ano', '1 Año'), ('12_mes', '12 Meses')], default='1_mes', max_length=20, null=True),
        ),
    ]
