# Generated by Django 4.2 on 2026-03-25 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_venta_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscripcion',
            name='objetivo_rutina',
            field=models.CharField(choices=[('bajar_peso', 'Bajar de peso'), ('mantener', 'Mantener peso'), ('subir_masa', 'Subir masa muscular')], default='mantener', help_text='Objetivo de la rutina personalizada', max_length=20),
        ),
    ]
