# Generated by Django 4.2.16 on 2026-04-01 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0003_suscripcion_objetivo_rutina'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('peso', 'Alcanzar un peso específico'), ('imc', 'Alcanzar un IMC específico'), ('rutina', 'Completar una rutina')], default='peso', max_length=20)),
                ('descripcion', models.CharField(help_text='Descripción de la meta', max_length=200)),
                ('peso_objetivo', models.DecimalField(blank=True, decimal_places=2, help_text='Peso objetivo en kg', max_digits=5, null=True)),
                ('fecha_objetivo', models.DateField(blank=True, help_text='Fecha límite para cumplir la meta', null=True)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('completada', 'Completada'), ('pausada', 'Pausada')], default='activa', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_completada', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meta del Usuario',
                'verbose_name_plural': 'Metas del Usuario',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='HistorialPeso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(decimal_places=2, help_text='Peso en kg', max_digits=5)),
                ('estatura', models.DecimalField(decimal_places=2, help_text='Estatura en metros', max_digits=3)),
                ('imc', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('rutina', models.CharField(blank=True, choices=[('bajar_peso', '🔥 Bajar de Peso'), ('subir_masa', '💪 Subir Masa Muscular'), ('mantener', '⚖️ Mantener Peso'), ('definir', '🥷 Definir Musculatura'), ('cardio', '❤️ Cardio y Resistencia'), ('subir_masa_perder_grasa', '⚡ Subir Masa y Perder Grasa')], help_text='Rutina activa en ese momento', max_length=30)),
                ('notas', models.TextField(blank=True, help_text='Notas opcionales sobre este registro')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_peso', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Peso',
                'verbose_name_plural': 'Historial de Pesos',
                'ordering': ['-fecha'],
            },
        ),
    ]
