# Generated by Django 4.2.16 on 2026-04-08 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0005_notificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la rutina')),
                ('nivel', models.CharField(choices=[('principiante', 'Principiante'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], default='principiante', max_length=20)),
                ('duracion_dias', models.PositiveIntegerField(default=30, help_text='Duración en días')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activa', models.BooleanField(default=True, help_text='Si está disponible para clientes')),
                ('imagen', models.ImageField(blank=True, help_text='Imagen representativa', null=True, upload_to='rutinas/')),
                ('creada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutinas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rutina',
                'verbose_name_plural': 'Rutinas',
                'db_table': 'rutinas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del ejercicio', max_length=150)),
                ('descripcion', models.TextField(blank=True, help_text='Instrucciones del ejercicio')),
                ('series', models.PositiveIntegerField(default=3, help_text='Número de series')),
                ('repeticiones', models.CharField(help_text='Repeticiones (ej: 12, 8-12)', max_length=50)),
                ('descanso', models.PositiveIntegerField(default=60, help_text='Descanso en segundos')),
                ('dia', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], help_text='Día de la semana', max_length=15)),
                ('orden', models.PositiveIntegerField(default=1, help_text='Orden dentro del día')),
                ('ejercicio_externo_id', models.PositiveIntegerField(blank=True, help_text='ID de ejercicio externo (API)', null=True)),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios', to='usuarios.rutina')),
            ],
            options={
                'verbose_name': 'Ejercicio',
                'verbose_name_plural': 'Ejercicios',
                'db_table': 'ejercicios',
                'ordering': ['dia', 'orden'],
            },
        ),
    ]
