# Generated by Django 4.2.16 on 2026-04-08 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_rutina_ejercicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutina',
            name='es_predeterminada',
            field=models.BooleanField(default=False, help_text='Rutina del sistema (no editable por admin)'),
        ),
    ]
