# Generated by Django 4.2.16 on 2026-04-08 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_rutina_es_predeterminada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercicio',
            name='ejercicio_externo_id',
            field=models.CharField(blank=True, help_text='ID de ejercicio externo (API)', max_length=100, null=True),
        ),
    ]
