# Generated by Django 4.2.16 on 2026-04-09 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_ejercicio_ejercicio_externo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='cedula',
            field=models.CharField(blank=True, help_text='Número de identificación', max_length=20),
        ),
        migrations.AddField(
            model_name='perfil',
            name='tarjeta',
            field=models.CharField(blank=True, help_text='Número de tarjeta/membresía', max_length=20),
        ),
    ]
