# Generated by Django 4.2.16 on 2026-04-18 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_add_cedula_tarjeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscripcion',
            name='acepto_terminos',
            field=models.BooleanField(default=False, help_text='El usuario aceptó términos y condiciones al comprar'),
        ),
        migrations.AddField(
            model_name='venta',
            name='acepto_terminos',
            field=models.BooleanField(default=False, help_text='El usuario aceptó términos y condiciones al comprar'),
        ),
    ]
