# Generated by Django 4.2.16 on 2026-07-02 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_suscripcion_acepto_terminos_venta_acepto_terminos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutina',
            name='nombre',
            field=models.CharField(choices=[('bajar_peso', 'Bajar Peso'), ('subir_masa', 'Subir Masa Muscular'), ('definicion', 'Definición Muscular'), ('cardio', 'Cardio'), ('resistencia', 'Resistencia'), ('funcional', 'Funcional'), ('adulto_mayor', 'Adulto Mayor'), ('rehabilitacion', 'Rehabilitación')], max_length=30, unique=True),
        ),
    ]
