# Generated by Django 4.2 on 2026-03-22 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='maquina_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='tiene_maquina',
            field=models.BooleanField(default=False),
        ),
    ]
