# Generated by Django 4.2.16 on 2026-04-01 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_maquina_id_producto_tiene_maquina'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_costo',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio de compra al proveedor', max_digits=10),
        ),
    ]
