# Generated by Django 4.2.16 on 2026-07-01 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_producto_precio_costo'),
    ]

    operations = [
    ]
