# Generated by Django 4.2.16 on 2026-07-01 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_fix_categoria'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='Categoria',
                    fields=[
                        ('id', models.BigAutoField(primary_key=True, serialize=False)),
                        ('nombre', models.CharField(max_length=50, unique=True)),
                        ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                        ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                        ('es_consumible', models.BooleanField(default=False)),
                    ],
                    options={
                        'db_table': 'categorias',
                    },
                ),
                migrations.AlterField(
                    model_name='producto',
                    name='categoria',
                    field=models.ForeignKey(blank=True, db_column='categoria_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='productos.categoria'),
                ),
            ],
        ),
    ]
