# Generated by Django 4.2 on 2026-03-22 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maquinaria',
            fields=[
                ('id_maquina', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('reparacion', 'En reparación'), ('venta', 'En venta'), ('vendido', 'Vendido')], default='activo', max_length=20)),
                ('motivo_salida', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'maquinaria',
            },
        ),
    ]
