# Generated by Django 4.2.16 on 2026-03-26 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_maquina_id_producto_tiene_maquina'),
        ('maquinaria', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maquinaria',
            options={'ordering': ['-id_maquina'], 'verbose_name': 'Maquinaria', 'verbose_name_plural': 'Maquinaria'},
        ),
        migrations.AddField(
            model_name='maquinaria',
            name='fecha_compra',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maquinaria',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='maquinaria/'),
        ),
        migrations.AddField(
            model_name='maquinaria',
            name='precio_compra',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio de compra en COP', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='maquinaria',
            name='precio_venta',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio de venta en COP', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='maquinaria',
            name='producto_vinculado',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maquina_origen', to='productos.producto'),
        ),
        migrations.AlterField(
            model_name='maquinaria',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('reparacion', 'En Reparacion'), ('venta', 'En Venta'), ('vendido', 'Vendido')], default='activo', max_length=20),
        ),
        migrations.AlterField(
            model_name='maquinaria',
            name='tipo',
            field=models.CharField(choices=[('cardio', 'Cardio'), ('fuerza', 'Fuerza'), ('funcional', 'Funcional'), ('pesas', 'Pesas y Discos'), ('accesorio', 'Accesorio'), ('otro', 'Otro')], default='otro', max_length=50),
        ),
    ]
