# Generated by Django 4.2.16 on 2026-04-05 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0007_frasemotivacional'),
        ('maquinaria', '0002_alter_maquinaria_options_maquinaria_fecha_compra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquinaria',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maquinarias', to='proveedores.proveedor'),
        ),
    ]
