# Generated by Django 4.2.16 on 2026-04-03 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_alter_proveedor_options_alter_proveedor_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_nombre', models.CharField(help_text='Nombre del producto a devolver', max_length=200)),
                ('cantidad', models.PositiveIntegerField(default=1, help_text='Cantidad de unidades')),
                ('motivo', models.CharField(choices=[('dañado', 'Producto Dañado'), ('vencido', 'Producto Vencido'), ('error', 'Error en el Pedido'), ('otro', 'Otro Motivo')], max_length=20)),
                ('descripcion', models.TextField(help_text='Descripción detallada del motivo de la devolución')),
                ('imagen', models.ImageField(blank=True, help_text='Imagen del producto', null=True, upload_to='devoluciones/')),
                ('fecha_devolucion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('completada', 'Completada')], default='pendiente', max_length=15)),
                ('notas_admin', models.TextField(blank=True, help_text='Notas internas del administrador')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoluciones', to='proveedores.proveedor')),
            ],
            options={
                'verbose_name': 'Devolución',
                'verbose_name_plural': 'Devoluciones',
                'db_table': 'devoluciones',
                'ordering': ['-fecha_devolucion'],
            },
        ),
    ]
