# Generated by Django 4.2.16 on 2026-04-03 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0004_devolucion_fecha_respuesta_devolucion_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolucion',
            name='respuesta_proveedor',
            field=models.TextField(blank=True, help_text='Motivo de la respuesta del proveedor'),
        ),
    ]
