# Generated by Django 4.2.16 on 2026-04-05 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0005_devolucion_respuesta_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
