# Generated by Django 4.2.16 on 2026-04-05 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0006_proveedor_ciudad'),
    ]

    operations = [
        migrations.CreateModel(
            name='FraseMotivacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frase', models.TextField()),
                ('autor', models.CharField(default='Anónimo', max_length=100)),
                ('categoria', models.CharField(default='fitness', max_length=50)),
                ('veces_usada', models.IntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'frases_motivacionales',
                'ordering': ['-veces_usada', '-fecha_creacion'],
            },
        ),
    ]
