# Generated by Django 4.2.16 on 2026-04-07 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_producto_precio_costo'),
        ('proveedores', '0007_frasemotivacional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devolucion',
            name='producto_nombre',
        ),
        migrations.AddField(
            model_name='devolucion',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devoluciones', to='productos.producto'),
        ),
    ]
