# Generated by Django 4.2.16 on 2026-04-07 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_producto_precio_costo'),
        ('proveedores', '0008_remove_devolucion_producto_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='productos',
            field=models.ManyToManyField(blank=True, related_name='proveedores', to='productos.producto'),
        ),
    ]
